### ISSUE TITLE
Integrate turvallisuusneuvonta

### ISSUE THREAD

**Issue by sustefil** [sthagen/turvallisuusneuvonta#10]
As discussed here:

https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/14#issuecomment-1039012590

Integrate the tests into cvrf2csaf.py:

https://github.com/sthagen/turvallisuusneuvonta

**Comment by sustefil** [comment]
sorry wrong repo :)

**Comment by sthagen** [comment]
No problem.
